// Command mkfixture mints the frozen, committed end-to-end fixtures that guard
// NBackup's on-disk format against accidental drift. It drives the real engine to
// produce a volume exactly as production would, then packs that volume's directory
// into a gzip-compressed tar under the engine package's testdata.
//
// The fixtures are deliberately NOT regenerated by the test suite: they are old
// bytes, and the format-survival test asserts today's reader still restores them.
// Re-mint them only when the format is changed on purpose (and review the diff to
// the .tar.gz — it is the visible signal that the format moved):
//
//	go run ./internal/tools/mkfixture
//
// GNU tar must be on PATH. Codec is always "none" (no compressor-binary dependency).
package main

import (
	"archive/tar"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	"github.com/Niloen/nbackup/internal/config"
	"github.com/Niloen/nbackup/internal/engine"
)

// fixtureDir is where the committed fixtures live, relative to the repo root.
const fixtureDir = "internal/engine/testdata/format"

// manifest describes one fixture: how to open its medium and what every recorded
// slot must restore to. The format-survival test reads it; keep the JSON tags in
// sync with the reader in internal/engine/format_fixture_test.go.
type manifest struct {
	Name       string        `json:"name"`
	MediumType string        `json:"medium_type"`
	Landing    string        `json:"landing"`
	ParamKey   string        `json:"param_key"` // medium option pointing at the unpacked dir: "path" (disk) or "dir" (tape)
	Codec      string        `json:"codec"`
	Restores   []restoreCase `json:"restores"`
}

type restoreCase struct {
	Slot   string            `json:"slot"`
	DLE    string            `json:"dle"`
	Files  map[string]string `json:"files"`
	Absent []string          `json:"absent,omitempty"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "mkfixture:", err)
		os.Exit(1)
	}
}

func run() error {
	if err := makeDiskFixture(); err != nil {
		return fmt.Errorf("disk-none-v1: %w", err)
	}
	if err := makeTapeFixture(); err != nil {
		return fmt.Errorf("tape-none-v1: %w", err)
	}
	return nil
}

// makeDiskFixture mints a disk volume holding a full then an incremental of one
// DLE (a deletion between them), locking both single and chain restore over the
// disk framing (clean payload + .hdr sidecar).
func makeDiskFixture() error {
	tmp, err := os.MkdirTemp("", "mkfixture-disk")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)

	src := filepath.Join(tmp, "src")
	mediumDir := filepath.Join(tmp, "medium")
	work := filepath.Join(tmp, "work")
	writeFile(src, "data/keep.txt", "v1")
	writeFile(src, "data/gone.txt", "temp")
	writeFile(src, "data/sub/nested.txt", "hi")

	cfg := &config.Config{
		Landing: "disk",
		Media:   map[string]config.Media{"disk": {Type: "disk", Params: map[string]string{"path": mediumDir}}},
		Sources: []config.DLE{{Host: "h", Path: "data"}},
		Workdir: work,
	}
	cfg.Compress.Codec = "none"

	dle := config.DLE{Host: "h", Path: "data"}.Name()
	var s1id, s2id string
	err = inDir(src, func() error {
		eng, err := engine.New(cfg)
		if err != nil {
			return err
		}
		s1, err := eng.Run(time.Date(2026, 6, 21, 0, 0, 0, 0, time.UTC), nil)
		if err != nil {
			return fmt.Errorf("full run: %w", err)
		}
		s1id = s1.ID

		// Change the tree so the incremental carries an update and a deletion. The
		// sleep clears tar's 1-second mtime granularity, as the engine tests do.
		time.Sleep(1100 * time.Millisecond)
		writeFile(src, "data/keep.txt", "v2")
		if err := os.Remove(filepath.Join(src, "data/gone.txt")); err != nil {
			return err
		}
		s2, err := eng.Run(time.Date(2026, 6, 22, 0, 0, 0, 0, time.UTC), nil)
		if err != nil {
			return fmt.Errorf("incremental run: %w", err)
		}
		s2id = s2.ID
		return nil
	})
	if err != nil {
		return err
	}

	man := manifest{
		Name: "disk-none-v1", MediumType: "disk", Landing: "disk", ParamKey: "path", Codec: "none",
		Restores: []restoreCase{
			{Slot: s1id, DLE: dle, Files: map[string]string{"keep.txt": "v1", "gone.txt": "temp", "sub/nested.txt": "hi"}},
			{Slot: s2id, DLE: dle, Files: map[string]string{"keep.txt": "v2", "sub/nested.txt": "hi"}, Absent: []string{"gone.txt"}},
		},
	}
	return writeFixture("disk-none-v1", mediumDir, man)
}

// makeTapeFixture mints a tape volume (a labeled file-0 plus an inline-header
// archive and seal), locking the tape framing — the 32 KB inline header block the
// disk medium never writes. It dumps to disk, then copies the slot onto the tape.
func makeTapeFixture() error {
	tmp, err := os.MkdirTemp("", "mkfixture-tape")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)

	src := filepath.Join(tmp, "src")
	diskDir := filepath.Join(tmp, "disk")
	tapeDir := filepath.Join(tmp, "tape")
	work := filepath.Join(tmp, "work")
	writeFile(src, "data/keep.txt", "v1")
	writeFile(src, "data/sub/nested.txt", "hi")

	cfg := &config.Config{
		Landing: "disk",
		Media: map[string]config.Media{
			"disk": {Type: "disk", Params: map[string]string{"path": diskDir}},
			"tape": {Type: "tape", Params: map[string]string{"dir": tapeDir}},
		},
		Sources: []config.DLE{{Host: "h", Path: "data"}},
		Workdir: work,
	}
	cfg.Compress.Codec = "none"

	dle := config.DLE{Host: "h", Path: "data"}.Name()
	var sid string
	err = inDir(src, func() error {
		eng, err := engine.New(cfg)
		if err != nil {
			return err
		}
		s, err := eng.Run(time.Date(2026, 6, 21, 0, 0, 0, 0, time.UTC), nil)
		if err != nil {
			return fmt.Errorf("dump: %w", err)
		}
		sid = s.ID
		if err := eng.LabelVolume("tape", "tape-0001", false, false, time.Date(2026, 6, 21, 0, 0, 0, 0, time.UTC), nil); err != nil {
			return fmt.Errorf("label tape: %w", err)
		}
		if err := eng.CopySlot(s.ID, "tape", false, nil); err != nil {
			return fmt.Errorf("copy to tape: %w", err)
		}
		return nil
	})
	if err != nil {
		return err
	}

	man := manifest{
		Name: "tape-none-v1", MediumType: "tape", Landing: "tape", ParamKey: "dir", Codec: "none",
		Restores: []restoreCase{
			{Slot: sid, DLE: dle, Files: map[string]string{"keep.txt": "v1", "sub/nested.txt": "hi"}},
		},
	}
	return writeFixture("tape-none-v1", tapeDir, man)
}

// writeFixture packs a minted volume directory into <fixtureDir>/<name>/volume.tar.gz
// and writes its manifest beside it.
func writeFixture(name, volumeDir string, man manifest) error {
	dir := filepath.Join(fixtureDir, name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	gzPath := filepath.Join(dir, "volume.tar.gz")
	if err := tarGz(volumeDir, gzPath); err != nil {
		return err
	}
	mb, err := json.MarshalIndent(man, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "manifest.json"), append(mb, '\n'), 0o644); err != nil {
		return err
	}
	if fi, err := os.Stat(gzPath); err == nil {
		fmt.Printf("wrote %s (%d bytes)\n", gzPath, fi.Size())
	}
	return nil
}

// tarGz writes every file under srcDir into outPath as a gzip-compressed tar, with
// names relative to srcDir. Gzip collapses the volume's zero padding (the 32 KB
// header blocks, tar's own block padding) to almost nothing, so the committed
// fixture stays tiny without ever storing raw padding in git.
func tarGz(srcDir, outPath string) error {
	f, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer f.Close()
	gz := gzip.NewWriter(f)
	tw := tar.NewWriter(gz)

	walkErr := filepath.Walk(srcDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(srcDir, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		hdr, err := tar.FileInfoHeader(info, "")
		if err != nil {
			return err
		}
		hdr.Name = filepath.ToSlash(rel)
		// Drop nondeterministic metadata so re-minting an unchanged volume yields a
		// stable archive (the medium's own timestamps already vary run to run).
		hdr.ModTime = time.Unix(0, 0).UTC()
		hdr.AccessTime = time.Time{}
		hdr.ChangeTime = time.Time{}
		hdr.Uid, hdr.Gid = 0, 0
		hdr.Uname, hdr.Gname = "", ""
		if err := tw.WriteHeader(hdr); err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			return nil
		}
		in, err := os.Open(path)
		if err != nil {
			return err
		}
		defer in.Close()
		_, err = io.Copy(tw, in)
		return err
	})
	if walkErr != nil {
		return walkErr
	}
	if err := tw.Close(); err != nil {
		return err
	}
	return gz.Close()
}

// inDir runs fn with the process working directory set to dir, restoring it after.
// The DLE source path is given relative ("data") so the DLE name is a clean,
// machine-independent "h-data" rather than embedding a temp path.
func inDir(dir string, fn func() error) error {
	prev, err := os.Getwd()
	if err != nil {
		return err
	}
	if err := os.Chdir(dir); err != nil {
		return err
	}
	defer os.Chdir(prev)
	return fn()
}

func writeFile(root, rel, content string) {
	full := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		panic(err)
	}
}
