package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/Niloen/nbackup/internal/config"
	"github.com/Niloen/nbackup/internal/sizeutil"
	"github.com/Niloen/nbackup/internal/transform/compress"
)

// initHeader tops the generated file; the example config stays the full tour.
const initHeader = `# NBackup configuration, generated by nb init.
# Every option (encryption, replication, drills, remote hosts, holding disk, …)
# is documented in nbackup.example.yaml and the README.
`

// newInitCmd implements `nb init`: the first-run wizard. It writes a starting
// config — interviewing on a terminal, or driven by flags for scripted use — by
// building the real config structs, validating the emitted file through the real
// loader, and refusing to overwrite an existing file. The output path is the
// global --config (default nbackup.yaml).
func newInitCmd(a *app) *cobra.Command {
	var (
		sources  []string
		to       string
		capacity string
		cycle    string
	)
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Write a starting nbackup.yaml (interactive, or via flags)",
		Long: "Create a starting config file at --config (default nbackup.yaml). On a terminal it " +
			"asks a few questions: what to back up, where runs land (a disk directory, an " +
			"object-store URL, or a tape directory/device), capacity, and cycle length. " +
			"For scripts, pass --source and --to instead. It never overwrites an existing " +
			"config, never asks for a secret value, and validates the file through the real " +
			"config loader before writing it.",
		Example: "  nb init\n" +
			"  nb init --source /home --source /etc --to /var/lib/nbackup/runs --capacity 500GB\n" +
			"  nb init --source /srv --to s3://backups?region=eu-north-1",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			out := a.cfgPath
			if _, err := os.Stat(out); err == nil {
				return fmt.Errorf("%s already exists — nb init never overwrites a config (edit it, or pass -c <new-path>)", out)
			}
			ans := initAnswers{Sources: sources, To: to, Capacity: capacity, Cycle: cycle}
			switch {
			case ans.To != "" && len(ans.Sources) > 0:
				// fully specified by flags: scripted use
			case ans.To != "" || len(ans.Sources) > 0:
				return fmt.Errorf("scripted init needs both --source and --to (or run nb init on a terminal with neither)")
			case stdinIsTerminal():
				if err := interview(&ans); err != nil {
					return err
				}
			default:
				return fmt.Errorf("no terminal to interview on and no flags given — pass --source and --to, or start from nbackup.example.yaml")
			}
			return writeInitConfig(out, ans)
		},
	}
	f := cmd.Flags()
	f.StringArrayVar(&sources, "source", nil, "path to back up (repeatable)")
	f.StringVar(&to, "to", "", "where runs land: a directory (disk), an object-store URL (s3://…), or a tape directory/device")
	f.StringVar(&capacity, "capacity", "", "space NBackup may use on the landing medium, e.g. 500GB (tape: per-cartridge size)")
	f.StringVar(&cycle, "cycle", "", `dump cycle: max time between fulls (default "7d")`)
	return cmd
}

// initAnswers collects the interview/flag inputs before they become a config.
type initAnswers struct {
	Sources  []string
	To       string
	Capacity string
	Cycle    string
	Notify   string // "" | "email" | "webhook"
	SMTPHost string
	MailFrom string
	MailTo   string
}

// interview asks the ~5 first-run questions on the terminal. Answers arrive via
// the shared stdinReader; a default is taken on a bare Enter.
func interview(ans *initAnswers) error {
	fmt.Println("nb init — a few questions; Enter takes the [default].")
	paths, err := ask("Paths to back up (space-separated)", "/home")
	if err != nil {
		return err
	}
	ans.Sources = strings.Fields(paths)
	if ans.To, err = ask("Where runs land: a directory, an object-store URL (s3://…),\n  or a tape directory/device", "./nbackup-runs"); err != nil {
		return err
	}
	capQ := "Capacity NBackup may use there (e.g. 500GB; empty = unbounded)"
	if kind, _ := destMedium(ans.To); kind == "tape" {
		capQ = "Per-cartridge size (volume_size, e.g. 6TB; empty = unbounded)"
	}
	if ans.Capacity, err = askValid(capQ, "", validCapacity); err != nil {
		return err
	}
	if ans.Cycle, err = askValid("Dump cycle: max time between full backups", "7d", validCycle); err != nil {
		return err
	}
	if ans.Notify, err = askValid("Alert on failures via email or webhook? (none/email/webhook)", "none", validNotify); err != nil {
		return err
	}
	switch ans.Notify {
	case "none":
		ans.Notify = ""
	case "email":
		if ans.SMTPHost, err = ask("  SMTP host", ""); err != nil {
			return err
		}
		if ans.MailFrom, err = ask("  From address", ""); err != nil {
			return err
		}
		if ans.MailTo, err = ask("  To address", ""); err != nil {
			return err
		}
	case "webhook":
		// The URL is usually a secret (Slack/Discord); only its env-var NAME is
		// stored, so there is nothing to ask for here.
	}
	return nil
}

// Per-question validators: each rejection is the format hint askValid re-prompts
// with, so a typo costs one line, not the whole interview.

// validCapacity accepts an empty answer (unbounded) or anything sizeutil parses.
func validCapacity(s string) error {
	if s == "" {
		return nil
	}
	if _, err := sizeutil.ParseBytes(s); err != nil {
		return fmt.Errorf("answer a size like 500GB or 1.5TB, or leave empty for unbounded — got %q", s)
	}
	return nil
}

// validCycle accepts a positive duration in the config's cycle syntax.
func validCycle(s string) error {
	if d, err := sizeutil.ParseDuration(s); err != nil || d <= 0 {
		return fmt.Errorf("answer a duration like 7d or 12h — got %q", s)
	}
	return nil
}

// validNotify accepts the three interview choices.
func validNotify(s string) error {
	switch s {
	case "none", "email", "webhook":
		return nil
	}
	return fmt.Errorf("answer none, email, or webhook — got %q", s)
}

// askValid asks until the answer validates, printing the validator's format hint
// and re-asking on a bad answer — one typo must not abort the interview and
// discard everything answered so far. A closed stdin still aborts (via ask), so
// a scripted pipe can never loop forever.
func askValid(question, def string, valid func(string) error) (string, error) {
	for {
		answer, err := ask(question, def)
		if err != nil {
			return "", err
		}
		if verr := valid(answer); verr != nil {
			fmt.Println(verr)
			continue
		}
		return answer, nil
	}
}

// ask prompts with a default and reads one line from the shared stdin reader.
func ask(question, def string) (string, error) {
	if def != "" {
		fmt.Printf("%s [%s]: ", question, def)
	} else {
		fmt.Printf("%s: ", question)
	}
	line, err := stdinReader.ReadString('\n')
	answer := strings.TrimSpace(line)
	if answer == "" {
		if err != nil {
			return "", fmt.Errorf("interview aborted (stdin closed)")
		}
		return def, nil
	}
	return answer, nil
}

// destMedium classifies the "where runs land" answer into a medium type and its
// connection param: an object-store URL scheme means cloud, a /dev node means a
// real tape drive, a "tape:<dir>" prefix a file-backed tape library, and anything
// else is a disk directory — the medium-neutral vocabulary of `media:`.
func destMedium(to string) (kind string, params map[string]string) {
	switch {
	case strings.HasPrefix(to, "s3://") || strings.HasPrefix(to, "gs://") || strings.HasPrefix(to, "azblob://"):
		return "cloud", map[string]string{"url": to}
	case strings.HasPrefix(to, "tape:"):
		return "tape", map[string]string{"dir": strings.TrimPrefix(to, "tape:")}
	case strings.HasPrefix(to, "/dev/"):
		return "tape", map[string]string{"device": to}
	default:
		return "disk", map[string]string{"path": to}
	}
}

// probeCompressor picks the config's compression scheme the way the engine's own
// preflight checks it (compress.Check probes the scheme binary on PATH): zstd when
// available, else gzip with a note, else none.
func probeCompressor() (scheme, note string) {
	if compress.Check("zstd", compress.Options{}) == nil {
		return "zstd", ""
	}
	if compress.Check("gzip", compress.Options{}) == nil {
		return "gzip", "zstd not found on PATH — using gzip (install zstd and set compress.scheme: zstd)"
	}
	return "none", "no compressor found on PATH — archives will be uncompressed (install zstd)"
}

// writeInitConfig turns the answers into a real config.Config, marshals it,
// validates the bytes through the real loader (a temp file beside the target),
// and only then moves it to out. So a file nb init wrote is a file nb loads.
func writeInitConfig(out string, ans initAnswers) error {
	kind, params := destMedium(ans.To)
	medium := config.Media{Type: kind, Params: params}
	if ans.Capacity != "" {
		if _, err := sizeutil.ParseBytes(ans.Capacity); err != nil {
			return fmt.Errorf("capacity: %w", err)
		}
		if kind == "tape" {
			params["volume_size"] = ans.Capacity
		} else {
			medium.Capacity = ans.Capacity
		}
	}

	// The workdir and state_dir default relative to the working directory, which
	// silently re-fulls when cron runs nb from elsewhere — pin them absolute,
	// beside the config file (the state_dir is precious; see nbackup.example.yaml).
	absDir, err := filepath.Abs(filepath.Dir(out))
	if err != nil {
		return err
	}

	cfg := &config.Config{
		Cycle:      ans.Cycle,
		Landing:    config.MediumList{kind},
		Media:      map[string]config.Media{kind: medium},
		Workdir:    filepath.Join(absDir, config.DefaultWorkdir),
		StateDir:   filepath.Join(absDir, config.DefaultStateDir),
		SecretsDir: filepath.Join(absDir, config.DefaultSecretsDir),
	}
	scheme, note := probeCompressor()
	cfg.Compress.Scheme = scheme
	for _, p := range ans.Sources {
		cfg.Sources = append(cfg.Sources, config.DLE{Host: "localhost", Path: p})
	}

	var secretHint string
	switch ans.Notify {
	case "email":
		cfg.Notify = config.NotifyConfig{Backends: map[string]config.NotifyBackend{
			"email": {
				Type: "smtp",
				Host: ans.SMTPHost,
				From: ans.MailFrom,
				To:   []string{ans.MailTo},
				// Only the env-var NAME is stored; nb init never asks for the value.
				PasswordEnv: "NBACKUP_SMTP_PASS",
			},
		}}
		secretHint = "email alerts read the SMTP password from $NBACKUP_SMTP_PASS at send time — export it in cron's environment"
	case "webhook":
		cfg.Notify = config.NotifyConfig{Backends: map[string]config.NotifyBackend{
			"webhook": {Type: "webhook", URLEnv: "NBACKUP_WEBHOOK_URL"},
		}}
		secretHint = "webhook alerts read the URL from $NBACKUP_WEBHOOK_URL at send time — export it in cron's environment"
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}

	// Validate the actual bytes through the real loader before they land at the
	// target path: a temp file in the same directory, renamed only on success.
	tmp, err := os.CreateTemp(filepath.Dir(out), ".nb-init-*.yaml")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if _, err := tmp.WriteString(initHeader + string(data)); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if _, err := config.Load(tmpPath); err != nil {
		return fmt.Errorf("generated config did not validate: %w", err)
	}
	if err := os.Rename(tmpPath, out); err != nil {
		return err
	}

	fmt.Printf("wrote %s (landing: %s, compression: %s)\n", out, kind, scheme)
	if note != "" {
		fmt.Println("note:", note)
	}
	if secretHint != "" {
		fmt.Println("note:", secretHint)
	}
	fmt.Println("\nnext steps:")
	if kind == "tape" {
		fmt.Println("  nb label tape <name>   # label a blank tape before the first dump")
	}
	fmt.Println("  nb check && nb plan    # verify the setup, then preview the first run")
	fmt.Println("  nb dump                # take the first backup")
	fmt.Printf("\ncron (nightly, unattended):\n  0 2 * * * cd %s && nb dump && nb drill --unattended; nb report --notify\n", absDir)
	return nil
}
