package engine

import (
	"archive/tar"
	"compress/gzip"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"testing"

	"github.com/Niloen/nbackup/internal/config"
)

// fixtureManifest mirrors the writer in internal/tools/mkfixture; keep the JSON
// tags in sync.
type fixtureManifest struct {
	Name       string `json:"name"`
	MediumType string `json:"medium_type"`
	Landing    string `json:"landing"`
	ParamKey   string `json:"param_key"`
	Codec      string `json:"codec"`
	Restores   []struct {
		Slot   string            `json:"slot"`
		DLE    string            `json:"dle"`
		Files  map[string]string `json:"files"`
		Absent []string          `json:"absent"`
	} `json:"restores"`
}

// TestFormatSurvivesRestore is the format-survival guard: each frozen fixture is a
// volume minted by an earlier build (committed as bytes, never regenerated by the
// suite). It unpacks the volume, opens today's engine over it, rebuilds the catalog
// from the volume alone, and asserts every recorded slot still restores to the
// expected tree. A one-sided change to the on-medium format — header fields, label,
// disk sidecar, tape inline block, seal record — breaks this even though the
// generated round-trip tests (which write and read with the same code) would not.
func TestFormatSurvivesRestore(t *testing.T) {
	dirs, err := filepath.Glob(filepath.Join("testdata", "format", "*"))
	if err != nil {
		t.Fatal(err)
	}
	if len(dirs) == 0 {
		t.Fatal("no fixtures under testdata/format (regenerate with `go run ./internal/tools/mkfixture`)")
	}
	for _, dir := range dirs {
		man := readManifest(t, filepath.Join(dir, "manifest.json"))
		t.Run(man.Name, func(t *testing.T) {
			volDir := filepath.Join(t.TempDir(), "volume")
			untarGz(t, filepath.Join(dir, "volume.tar.gz"), volDir)

			cfg := &config.Config{
				Landing: man.Landing,
				Media:   map[string]config.Media{man.Landing: {Type: man.MediumType, Params: map[string]string{man.ParamKey: volDir}}},
				Sources: []config.DLE{{Host: "h", Path: "data"}}, // unused by restore; satisfies a non-empty config
				Workdir: t.TempDir(),                             // a fresh catalog, forcing a rebuild from the volume
			}
			cfg.Compress.Codec = man.Codec

			eng, err := New(cfg)
			if err != nil {
				t.Fatalf("open engine on fixture: %v", err)
			}
			if m, err := eng.methodForDumpType(config.DefaultDumpType); err != nil || m.Check() != nil {
				t.Skipf("GNU tar not available")
			}
			if _, err := eng.RebuildCatalog(nil); err != nil {
				t.Fatalf("rebuild catalog from fixture volume: %v", err)
			}

			for _, rc := range man.Restores {
				dest := t.TempDir()
				if err := eng.Restore(rc.Slot, rc.DLE, dest, nil); err != nil {
					t.Fatalf("restore %s %s: %v", rc.Slot, rc.DLE, err)
				}
				for rel, want := range rc.Files {
					assertContent(t, filepath.Join(dest, rel), want)
				}
				for _, rel := range rc.Absent {
					if _, err := os.Stat(filepath.Join(dest, rel)); !os.IsNotExist(err) {
						t.Errorf("%s should be absent after restoring %s, stat err = %v", rel, rc.Slot, err)
					}
				}
			}
		})
	}
}

// TestFixtureSizesStayTiny fails if any committed testdata blob exceeds the cap, so
// a raw 32 KB header block (or any other un-gzipped volume) can never be checked in
// by accident. Fixtures are gzip-compressed volumes whose zero padding collapses to
// well under this; if a real fixture legitimately grows past it, raise the cap
// deliberately rather than committing bloat.
func TestFixtureSizesStayTiny(t *testing.T) {
	const cap = 8 * 1024
	err := filepath.Walk("testdata", func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || filepath.Ext(path) == ".json" {
			return nil // manifests are small text and exempt
		}
		if info.Size() > cap {
			t.Errorf("%s is %d bytes (> %d cap); commit fixtures gzip-compressed, never raw padded blocks", path, info.Size(), cap)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
}

func readManifest(t *testing.T, path string) fixtureManifest {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var m fixtureManifest
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	return m
}

// untarGz unpacks a gzip-compressed tar into destDir.
func untarGz(t *testing.T, gzPath, destDir string) {
	t.Helper()
	f, err := os.Open(gzPath)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	gz, err := gzip.NewReader(f)
	if err != nil {
		t.Fatal(err)
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatal(err)
		}
		target := filepath.Join(destDir, filepath.FromSlash(hdr.Name))
		if hdr.FileInfo().IsDir() {
			if err := os.MkdirAll(target, 0o755); err != nil {
				t.Fatal(err)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			t.Fatal(err)
		}
		out, err := os.Create(target)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := io.Copy(out, tr); err != nil {
			out.Close()
			t.Fatal(err)
		}
		if err := out.Close(); err != nil {
			t.Fatal(err)
		}
	}
}
